In [3]:
import tensorflow as tf
import numpy as np


In [4]:
#import sys

#!{sys.executable} --version
#!{sys.executable} -m pip install jupyterthemes
#!{sys.executable} -m pip install upgrade jupyterthemes


In [5]:
@tf.function
def np_random():
    a = np.random.randn(3,3)
    tf.print(a)

@tf.function
def tf_random():
    a = tf.random.normal((3,3))
    tf.print(a)

In [6]:
#np_random每次执行都是一样的结果。

np_random()
np_random()

array([[ 0.99049819, -1.66215524,  0.54395874],
       [ 0.18096649,  1.23080497,  1.74319667],
       [ 0.31318186,  1.12465654,  1.47303187]])
array([[ 0.99049819, -1.66215524,  0.54395874],
       [ 0.18096649,  1.23080497,  1.74319667],
       [ 0.31318186,  1.12465654,  1.47303187]])


In [7]:
#tf_random每次执行都会有重新生成随机数。

tf_random()
tf_random()

[[-0.280161 -0.51946938 1.54797697]
 [-0.362261 2.26937079 0.602325618]
 [1.49748135 0.878996193 -2.04024911]]
[[0.412267059 -0.492778 0.381385326]
 [0.191651493 -1.26837552 1.78331041]
 [-0.376318067 -1.44385517 -0.897339761]]


# 避免在@tf.function修饰的函数内部定义tf.Variable

In [8]:
x = tf.Variable(1.0, dtype = tf.float32)



@tf.function

def outer_var():
    x.assign_add(1.0)
    tf.print(x)
    return(x)

outer_var()
outer_var()


2
3


<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [9]:
@tf.function
def inner_var():
    x = tf.Variable(1.0,dtype = tf.float32)   ###定义函数需要在外部

    x.assign_add(1.0)
    tf.print(x)
    return(x)

##执行报错
#inner_var()

# 3,被@tf.function修饰的函数不可修改该函数外部的Python列表或字典等结构类型变量。

In [10]:
tensor_list = []

def append_tensor(x):
    tensor_list.append(x)
    return tensor_list

append_tensor(tf.constant(5))
append_tensor(tf.constant(6))


[<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(), dtype=int32, numpy=6>]

In [11]:
tensor_list = []


@tf.function    #结果不符合预期因为这一行
def append_tensor(x):
    tensor_list.append(x)
    return tensor_list

append_tensor(tf.constant(5))
append_tensor(tf.constant(6))

[<tf.Tensor: shape=(), dtype=int32, numpy=6>]

In [12]:
tf.range(3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2])>

In [13]:
@tf.function(autograph = True)
def myadd(a,b):
    for i in tf.range(3):
        tf.print(i)
    c = a+b
    print('tracing')
    return c

In [14]:
myadd(tf.constant('hello'),tf.constant('world'))

tracing
0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'helloworld'>

In [15]:
myadd(tf.constant('good'),tf.constant('morning'))

0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'goodmorning'>

In [16]:
myadd(tf.constant(1),tf.constant(2))



tracing
0
1
2


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [17]:
myadd(tf.constant(1),tf.constant(2))


0
1
2


<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [18]:
myadd("hello","world")

tracing
0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'helloworld'>

In [19]:
myadd("good","morning")


tracing
0
1
2


<tf.Tensor: shape=(), dtype=string, numpy=b'goodmorning'>

tracing
0
1
2


<tf.Tensor: shape=(), dtype=int32, numpy=9>