In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
a = tf.constant([[1.0,2],[-3,4]])
b = tf.constant([[5.0,6],[7,8]])
a+b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [ 4., 12.]], dtype=float32)>

In [3]:
a-b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ -4.,  -4.],
       [-10.,  -4.]], dtype=float32)>

In [4]:
a*b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[  5.,  12.],
       [-21.,  32.]], dtype=float32)>

In [5]:
a/b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.2       ,  0.33333334],
       [-0.42857143,  0.5       ]], dtype=float32)>

In [6]:
a**2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>

In [7]:
a**(0.5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.       , 1.4142135],
       [      nan, 2.       ]], dtype=float32)>

In [8]:
a%3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [-0.,  1.]], dtype=float32)>

In [9]:
tf.math.mod(a,3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [-0.,  1.]], dtype=float32)>

In [10]:
a//3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.,  0.],
       [-1.,  1.]], dtype=float32)>

In [11]:
a>=2

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False,  True]])>

In [12]:
(a>=2)&(a<=3)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False,  True],
       [False, False]])>

In [13]:
(a>=2)|(a<=3)

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True]])>

In [14]:
a == 6

<tf.Tensor: shape=(2, 2), dtype=bool, numpy=
array([[False, False],
       [False, False]])>

In [15]:
tf.sqrt(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.99999994, 1.4142134 ],
       [       nan, 1.9999999 ]], dtype=float32)>

In [16]:
a = tf.constant([1.0,8.0])
b = tf.constant([5.0,6.0])
c = tf.constant([6.0,7.0])
tf.add_n([a,b,c])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12., 21.], dtype=float32)>

In [17]:
tf.maximum(a,b)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 8.], dtype=float32)>

In [18]:
tf.print(tf.minimum(a,b))

[1 6]


# 向量运算 许多都以reduce开头

In [19]:
a = tf.range(1,10)

tf.print(tf.reduce_sum(a))
tf.print(tf.reduce_mean(a))
tf.print(tf.reduce_max(a))
tf.print(tf.reduce_min(a))
tf.print(tf.reduce_prod(a))

45
5
9
1
362880


In [20]:
b = tf.reshape(a,(3,3))
b

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [21]:
tf.reduce_sum(b,axis = 1,keepdims=True)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 6],
       [15],
       [24]])>

In [22]:
tf.reduce_sum(b,axis = 0,keepdims=True)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[12, 15, 18]])>

In [23]:
#bool 类型（0和1）的reduce

p = tf.constant([True,False,True])
q = tf.constant([False,False,True])
tf.print(tf.reduce_all(p))
tf.print(tf.reduce_any(q))

0
1


In [24]:
#利用tf.foldr实现tf.reduce_sum

s = tf.foldr(lambda a, b:a+b, tf.range(5))
s

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [25]:
a = tf.constant([1,3,7,5,4,8])
values, indices = tf.math.top_k(a,4,sorted = True)  
tf.print(values)
tf.print(indices)

[8 7 5 4]
[5 2 3 4]


In [27]:
tf.print(tf.math.top_k(a,4))   #returns two values here

TopKV2(values=[8 7 5 4], indices=[5 2 3 4])


In [30]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[2,0],[0,2]])
a@b   # same as tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]])>

In [31]:
a = tf.constant([[1.0,2],[3,4]])
tf.transpose(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>

In [32]:
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [33]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [35]:
tf.linalg.eigvalsh(a)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.8541021,  5.854102 ], dtype=float32)>

In [37]:
q,r = tf.linalg.qr(a)
tf.print(q)
tf.print(r)
tf.print(q@r)

[[-0.316227794 -0.948683321]
 [-0.948683321 0.316227734]]
[[-3.1622777 -4.4271884]
 [0 -0.632455349]]
[[1.00000012 1.99999976]
 [3 4]]


In [38]:
a = tf.constant([1,2,3])
b = tf.constant([[0,0,0],[1,1,1],[2,2,2]])
b + a  #等价于 b + tf.broadcast_to(a,b.shape)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])>

In [39]:
tf.broadcast_to(a,b.shape)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [40]:
#计算广播后计算结果的形状，静态形状，TensorShape类型参数
tf.broadcast_static_shape(a.shape,b.shape)

TensorShape([3, 3])

In [41]:
c = tf.constant([1,2,3])
d = tf.constant([[1],[2],[3]])
tf.broadcast_to(c,[3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])>

In [42]:
tf.broadcast_to(d,[3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])>

In [43]:
c+d

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])>

In [44]:
tf.broadcast_to(c,[3,3])+tf.broadcast_to(d,[3,3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])>