In [73]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
x = tf.constant('hello')
y = tf.constant('world')
z = tf.strings.join([x,y], separator = ' ')
tf.print(z)

hello world


In [3]:
def strjoin(x,y):
    z =  tf.strings.join([x,y],separator = " ")
    tf.print(z)
    return z

result = strjoin(tf.constant("hello"),tf.constant("world"))
print(result)

hello world
tf.Tensor(b'hello world', shape=(), dtype=string)


In [4]:
import tensorflow as tf

# 使用autograph构建静态图

@tf.function
def strjoin(x,y):
    z =  tf.strings.join([x,y],separator = " ")
    tf.print(z)
    return z

result = strjoin(tf.constant("hello"),tf.constant("world"))

print(result)

hello world
tf.Tensor(b'hello world', shape=(), dtype=string)


In [5]:
%load_ext tensorboard


In [6]:
def f(x):   
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    
    # 自变量转换成tf.float32
    #x = tf.cast(x,tf.float32)
    with tf.GradientTape() as tape:
        tape.watch(x)             
        y = a*tf.pow(x,2)+b*x+c
    dy_dx = tape.gradient(y,x) 
    
    return((dy_dx,y))

tf.print(f(tf.constant(0.0)))
tf.print(f(tf.constant(1.0)))

(-2, 1)
(0, 0)


In [7]:
x = tf.Variable(0.0, dtype = tf.float32)
def f():
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    y = a*tf.pow(x,2) + b*x + c
    return(y)

optimizer = tf.keras.optimizers.SGD(learning_rate = 0.01)
for _ in range(10000):
    optimizer.minimize(f, [x])

tf.print('y=',f(),'x=', x)

y= 0 x= 0.999998569


# @tf.function 速度快

In [8]:
x = tf.Variable(0.0,name = "x",dtype = tf.float32)
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

@tf.function
def minimizef():
    a = tf.constant(1.0)
    b = tf.constant(-2.0)
    c = tf.constant(1.0)
    
    for _ in tf.range(10000): #注意autograph时使用tf.range(1000)而不是range(1000)
        with tf.GradientTape() as tape:
            y = a*tf.pow(x,2) + b*x + c
        dy_dx = tape.gradient(y,x)
        optimizer.apply_gradients(grads_and_vars=[(dy_dx,x)])
        
    y = a*tf.pow(x,2) + b*x + c
    return y

tf.print(minimizef())
tf.print(x)

0
0.999998569


In [9]:
a = tf.constant([1,2,3], dtype = tf.float32)
tf.print(a)

[1 2 3]


In [10]:
b = tf.range(1,10, delta = 2)
tf.print(b)

[1 3 5 7 9]


In [11]:
c = tf.linspace(0.0,2*3.14,100)
tf.print(c)

[0 0.0634343475 0.126868695 ... 6.15313148 6.21656609 6.28]


In [12]:
d = tf.zeros([3,3])
#d = tf.zeros((3,3))        Same
tf.print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
a = tf.ones((3,3))
b = tf.zeros_like(a, dtype = tf.float32)
tf.print(a)
tf.print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
c = tf.fill((3,2),6)
tf.print(c)

[[6 6]
 [6 6]
 [6 6]]


In [15]:
tf.random.set_seed(1.0)
a = tf.random.uniform([5,5], minval = 0, maxval = 10)
tf.print(a)

a.numpy()

[[1.65130854 9.01481247 6.30974197 4.34546089 2.9193902]
 [6.42502069 9.75785446 4.35099506 6.60101891 6.0489583]
 [6.36631489 6.14448786 8.89334869 6.27761745 5.31975031]
 [0.259782076 4.40875053 2.52670765 8.86223221 8.87293434]
 [7.87281609 0.595519543 0.710938 3.08414698 2.51182675]]


array([[1.6513085 , 9.014812  , 6.309742  , 4.345461  , 2.9193902 ],
       [6.4250207 , 9.757854  , 4.350995  , 6.601019  , 6.0489583 ],
       [6.366315  , 6.144488  , 8.893349  , 6.2776175 , 5.3197503 ],
       [0.25978208, 4.4087505 , 2.5267076 , 8.862232  , 8.872934  ],
       [7.872816  , 0.59551954, 0.710938  , 3.084147  , 2.5118268 ]],
      dtype=float32)

In [16]:
tf.random.set_seed(1.0)

b = tf.random.normal((3,3),mean = 0.0, stddev = 1.0)
tf.print(b)

[[-1.10122025 1.54575169 0.383644]
 [-0.879657865 -1.2246722 -0.981121123]
 [0.0878078267 -0.203260377 -0.558156192]]


In [17]:
#正态分布随机，剔除2倍方差以外数据重新生成
c = tf.random.truncated_normal((5,5),mean = 0,stddev = 1, dtype = tf.float32)
tf.print(c)

[[0.403087884 -1.0880208 -0.0630953535 1.33655667 -0.166902035]
 [0.985428274 -0.201567009 1.33069396 0.482788384 -0.468631625]
 [0.830428779 -0.64412874 1.01190746 0.466679752 -0.567880094]
 [-1.74263501 0.316212177 -0.631055892 0.50597626 -1.21443057]
 [0.0597660579 0.0369502194 0.88362354 1.8155154 0.142478839]]


In [19]:
I = tf.eye(3,3)
tf.print(I)
tf.print(' ')
t = tf.linalg.diag([1,2,3])
tf.print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
 
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [20]:
tf.random.set_seed(3)
t = tf.random.uniform((5,5), minval = 0, maxval = 10, dtype = tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [23]:
t[0]
tf.print(t[0])          #第一行
tf.print(t[-1])         #最后一行

[4 7 4 2 9]
[3 7 0 0 3]


In [27]:
tf.print(t[1,2])    #第2行第3列
tf.print(t[1][2])

2
2


In [30]:
tf.print(t[1:4,:])           #切片
tf.print(tf.slice(t,[1,0],[3,5]))

[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]
[[9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]]


In [32]:
#可以使用索引和切片修改部分元素
x = tf.Variable([[1,2],[3,4]], dtype = tf.float32)
x[1,:].assign(tf.constant([0.0,0.0]))
tf.print(x)

[[1 2]
 [0 0]]


In [34]:
a = tf.random.uniform([3,3,3],minval = 0, maxval = 10, dtype = tf.int32)
tf.print(a)

[[[2 2 6]
  [5 7 6]
  [4 8 6]]

 [[4 6 3]
  [8 1 7]
  [3 1 3]]

 [[2 1 6]
  [3 1 8]
  [9 3 7]]]


In [35]:
tf.print(a[...,1])  #取第二列


[[2 7 8]
 [6 1 1]
 [1 1 3]]


In [36]:
# 4x7x10  四个班级 每个班级10个学生 每个学生7门课程
scores = tf.random.uniform((4,10,7),minval = 0, maxval = 100, dtype = tf.int32)
tf.print(scores)

[[[0 64 96 ... 65 28 30]
  [16 99 74 ... 26 5 39]
  [12 48 9 ... 34 76 10]
  ...
  [70 79 37 ... 72 38 31]
  [65 55 44 ... 31 23 64]
  [88 59 9 ... 64 66 92]]

 [[11 24 9 ... 16 35 59]
  [46 46 87 ... 38 62 36]
  [37 52 47 ... 2 51 48]
  ...
  [74 95 6 ... 49 9 54]
  [67 47 74 ... 11 68 6]
  [92 29 27 ... 59 99 71]]

 [[78 37 24 ... 54 9 79]
  [77 99 5 ... 97 53 84]
  [25 26 89 ... 74 22 75]
  ...
  [94 67 77 ... 97 56 38]
  [61 44 50 ... 72 87 44]
  [48 67 96 ... 60 23 82]]

 [[64 74 80 ... 49 58 12]
  [19 51 31 ... 57 39 67]
  [16 31 46 ... 94 50 13]
  ...
  [20 81 89 ... 4 85 66]
  [90 19 14 ... 99 27 96]
  [35 63 52 ... 34 59 64]]]


In [40]:
#axis =1 抽取所有班级中学生0,5,9的所有成绩               axis=0即为抽取班级
p = tf.gather(scores, [0,5,9],axis =1)
tf.print(p)

[[[0 64 96 ... 65 28 30]
  [43 38 66 ... 7 7 65]
  [88 59 9 ... 64 66 92]]

 [[11 24 9 ... 16 35 59]
  [94 3 55 ... 4 93 52]
  [92 29 27 ... 59 99 71]]

 [[78 37 24 ... 54 9 79]
  [95 17 83 ... 99 84 96]
  [48 67 96 ... 60 23 82]]

 [[64 74 80 ... 49 58 12]
  [82 71 32 ... 49 39 28]
  [35 63 52 ... 34 59 64]]]


In [41]:
q = tf.gather(tf.gather(scores,[0,5,9],axis =1),[1,3,6],axis = 2)
tf.print(q)

[[[64 49 30]
  [38 4 65]
  [59 25 92]]

 [[24 58 59]
  [3 30 52]
  [29 76 71]]

 [[37 59 79]
  [17 0 96]
  [67 84 82]]

 [[74 83 12]
  [71 36 28]
  [63 84 64]]]


In [44]:
#第0班级第0学生，第2班级第四学生，第三班级第六学生所有成绩
s = tf.gather_nd(scores, indices = [(0,0),(2,4),(3,6)])
s
tf.print(s)

[[0 64 96 ... 65 28 30]
 [58 58 96 ... 51 33 64]
 [8 43 24 ... 87 79 10]]


In [50]:
## axis = 1 所有班级第0,5,9个学生所有成绩
p = tf.boolean_mask(scores,[True,False,False,False,False,True,False,False,False,True],axis = 1)
tf.print(p)

[[[0 64 96 ... 65 28 30]
  [43 38 66 ... 7 7 65]
  [88 59 9 ... 64 66 92]]

 [[11 24 9 ... 16 35 59]
  [94 3 55 ... 4 93 52]
  [92 29 27 ... 59 99 71]]

 [[78 37 24 ... 54 9 79]
  [95 17 83 ... 99 84 96]
  [48 67 96 ... 60 23 82]]

 [[64 74 80 ... 49 58 12]
  [82 71 32 ... 49 39 28]
  [35 63 52 ... 34 59 64]]]


In [53]:
#利用tf.boolean_mask实现布尔索引

c = tf.constant([[-1,1,-1],[2,2,0],[3,-3,3]],dtype = tf.int32)
tf.print(c, '\n')

tf.print(tf.boolean_mask(c,c < 0),'\n')
tf.print(c[c<0])

[[-1 1 -1]
 [2 2 0]
 [3 -3 3]] 

[-1 -1 -3] 

[-1 -1 -3]


In [75]:
#找到张量中小于0的元素，将其转化成nan得到新的张量

a = tf.constant([[-1,-1,-1],[-2,2,0],[-3,-3,3]],dtype = tf.float32)


c = tf.constant([[-1,1,-1],[2,2,0],[3,-3,3]],dtype = tf.float32)
d = tf.where(c < 0, tf.fill(c.shape,np.nan),c)
d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[nan,  1., nan],
       [ 2.,  2.,  0.],
       [ 3., nan,  3.]], dtype=float32)>

In [76]:
indices = tf.where(c<0)
indices

<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [2, 1]], dtype=int64)>

In [77]:
# scatter_nd(indices, updates, shape, name=None) 将新数据映射到default为0的矩阵上

indices = tf.where(c<0)
tf.scatter_nd(indices, tf.gather_nd(c,indices),c.shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.,  0., -1.],
       [ 0.,  0.,  0.],
       [ 0., -3.,  0.]], dtype=float32)>

# 维度变化

In [84]:
#tf.reshape  
#tf.squeeze 减少维度
#tf.expand_dims  增加维度
#tf.transpose   交换维度

In [100]:
a = tf.random.uniform(shape = [1,3,3,2],minval = 0, maxval = 255, dtype = tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[158 90]
   [89 14]
   [59 209]]

  [[91 164]
   [239 138]
   [156 95]]

  [[48 40]
   [0 238]
   [3 22]]]]


In [101]:
b = tf.reshape(a,(3,6))
tf.print(b.shape)
tf.print(b)

TensorShape([3, 6])
[[158 90 89 14 59 209]
 [91 164 239 138 156 95]
 [48 40 0 238 3 22]]


In [99]:
v = np.random.normal(0,1,10)
np.reshape(v,(2,5))

array([[ 1.88159327,  0.67306102,  0.3840516 , -0.95047955,  0.21198794],
       [ 0.84571777, -1.21950305, -0.011498  ,  0.02696512,  0.42271133]])

In [102]:
s = tf.squeeze(a)
tf.print(s.shape)
tf.print(s)

TensorShape([3, 3, 2])
[[[158 90]
  [89 14]
  [59 209]]

 [[91 164]
  [239 138]
  [156 95]]

 [[48 40]
  [0 238]
  [3 22]]]


In [104]:
d = tf.expand_dims(s,axis = 0)
d

<tf.Tensor: shape=(1, 3, 3, 2), dtype=int32, numpy=
array([[[[158,  90],
         [ 89,  14],
         [ 59, 209]],

        [[ 91, 164],
         [239, 138],
         [156,  95]],

        [[ 48,  40],
         [  0, 238],
         [  3,  22]]]])>

In [109]:
a = tf.random.uniform(shape=[100,600,600,4],minval=0,maxval=255,dtype=tf.int32)
tf.print(a.shape)

s= tf.transpose(a ,perm=[3,1,2,0])
tf.print(s.shape)



TensorShape([100, 600, 600, 4])
TensorShape([4, 600, 600, 100])


# 合并分割

In [110]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

tf.concat([a,b,c],axis = 0)

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.]], dtype=float32)>

In [111]:
tf.concat([a,b,c], axis = 1)

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 1.,  2.,  5.,  6.,  9., 10.],
       [ 3.,  4.,  7.,  8., 11., 12.]], dtype=float32)>

In [112]:
tf.stack([a,b,c])


<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [113]:
tf.stack([a,b,c],axis=1)


<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]],

       [[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]], dtype=float32)>

In [115]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

d = tf.concat([a,b,c],axis = 0)

tf.split(d,3,axis = 0)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]

In [116]:
tf.split(d,[2,2,2],axis = 0) #指定每份的记录数量


[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[5., 6.],
        [7., 8.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[ 9., 10.],
        [11., 12.]], dtype=float32)>]